# Launch with launch_cf -A UCIE0001 -l walltime=12:00:00 --steps-per-node 3 --ppn 36 --nthreads 12 --mem 235GB --queue casper -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/cmdfile_runreplicates_csv_iland2.1.sh
# Launch with launch_cf -A UCIE0001 -l walltime=12:00:00 --steps-per-node 3 --ppn 128 --nthreads 40 --mem 235GB -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/cmdfile_runreplicates_csv_iland2.1.sh
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_01/landscape_alaska_01_1950-1980spinup.xml 12 12 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_02/landscape_alaska_02_1950-1980spinup.xml 12 12 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_03/landscape_alaska_03_1950-1980spinup.xml 12 12 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_04/landscape_alaska_04_1950-1980spinup.xml 12 12 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_05/landscape_alaska_05_1950-1980spinup.xml 12 12 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 1 1 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 2 2 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 3 3 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 4 4 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 5 5 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 6 6 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 7 7 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 8 8 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 9 9 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 10 10 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 11 11 300
bash /glade/work/qasena/landscape_init_ak_can/run_iland_csv_cpxml_apptainer.sh /glade/work/qasena/landscape_init_ak_can/landscape_alaska_06/landscape_alaska_06_1950-1980spinup.xml 12 12 300