# /glade/work/benkirk/repos/NCAR-pbstools/bin/launch_cf -A UCIE0001 -l walltime=4:00:00 --steps-per-node 6 --ppn 36 --nthreads 6 --mem 235GB --queue casper -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/analysis-scripts/cmdfile_process_seed_dens.sh
# /glade/work/benkirk/repos/NCAR-pbstools/bin/launch_cf -A UCIE0001 -l walltime=1:00:00 --nthreads 20 --ppn 128 --steps-per-node 6 --mem 235GB -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/analysis-scripts/cmdfile_process_seed_dens.sh
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_02_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_03_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_04_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_05_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 1
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 2
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 3
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 4
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 5
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 6
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 7
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 8
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 9
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 10
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 11
# module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_06_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_onlysimfalse_yr_1_iLand2.1" 12
