# /glade/work/benkirk/repos/NCAR-pbstools/bin/launch_cf -A UCIE0001 -l walltime=4:00:00 --steps-per-node 3 --ppn 36 --nthreads 12 --mem 235GB --queue casper -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/analysis-scripts/cmdfile_process_seed_dens.sh
# /glade/work/benkirk/repos/NCAR-pbstools/bin/launch_cf -A UCIE0001 -l walltime=2:00:00 --steps-per-node 4 --ppn 20 --nthreads 5 --mem 235GB --queue casper -l job_priority=economy /glade/work/qasena/landscape_init_ak_can/analysis-scripts/cmdfile_process_seed_dens.sh
# /glade/work/benkirk/repos/NCAR-pbstools/bin/launch_cf -A UCIE0001 -l walltime=2:00:00 --steps-per-node 10 --mem 235GB -l  --queue casper job_priority=economy /glade/work/qasena/landscape_init_ak_can/analysis-scripts/cmdfile_process_seed_dens.sh
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_iLand2.0" 1
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_iLand2.0" 2
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_iLand2.0" 3
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_iLand2.0" 4
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_31_iLand2.0" 1
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_31_iLand2.0" 2
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_31_iLand2.0" 3
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_1_iLand2.1" 1
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_1_iLand2.1" 2
module purge; module load conda; conda activate my-r-4.4; Rscript /glade/work/qasena/landscape_init_ak_can/analysis-scripts/process_seed_dens.R "landscape_alaska_01_1950-1980spinup" "NorEsm2-MMssp126_dbh2.5_yr_1_iLand2.1" 3
