project:
  type: default
  output-dir: htmls
  render:
#    - area_dominated.qmd
#    - seedling_density.qmd
#    - SOL_postfire.qmd
#    - debug_summaries.qmd
#    - water_daily_resp_debug.qmd
#    - spatial_tests.qmd
#    - spinup_seeddens.qmd
#    - spinup_area_dom.qmd
#    - spinup_basal_area.qmd
#    - spinup_prop_dom.qmd
    - landcover_years.qmd
    
embed-resources: true
format:
  html:
    code-fold: false
    toc: true
    theme:
      light: flatly
      dark: darkly

execute: 
  cache: false
